[buildPlans.iosevka-fusion]
family      = "Iosevka Fusion"
spacing     = "fixed"
serifs      = "sans"

[buildPlans.iosevka-fusion.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "curly-serifless"
capital-q = "crossing"
capital-r = "curly-serifless"

c = "serifless"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook"
y = "cursive-flat-hook-serifless"

zero = "oval-slashed-split"
five = "oblique-upper-left-bar"
eight = "crossing-asymmetric"

diacritic-dot = "square"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "closed"
at = "threefold-tall"
dollar = "through"
percent = "dots"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
cent = "through"

[buildPlans.iosevka-fusion.variants.upright]
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-earless-corner"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
u = "toothless-corner-serifless"

one = "base"
two = "straight-neck"
four = "semi-open"
six = "straight-bar"
nine = "straight-bar"

[buildPlans.iosevka-fusion.variants.italic]
b = "toothed-serifless"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
k = "curly-serifless"
v = "curly-serifless"
w = "curly-serifless"
x = "curly-serifless"
z = "curly-serifless"

one = "no-base"
two = "curly-neck"
four = "closed"
six = "closed-contour"
nine = "closed-contour"

[buildPlans.iosevka-fusion.weights.thin]
shape = 100
menu  = 100
css   = 100

[buildPlans.iosevka-fusion.weights.extralight]
shape = 200
menu  = 200
css   = 200

[buildPlans.iosevka-fusion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevka-fusion.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-fusion.weights.semibold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-fusion.weights.heavy]
shape = 900
menu  = 900
css   = 900

[buildPlans.iosevka-fusion.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-fusion.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.iosevka-fusion.metric-override]
leading = 1350
sb = 60
xHeight = 530
