[buildPlans.iosevka-fusion]
family  = "Iosevka Fusion"
spacing = "fixed"
serifs  = "sans"

[buildPlans.iosevka-fusion.variants.design]
capital-a = "curly-motion-serifed"
capital-b = "standard-unilateral-motion-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-motion-serifed"
capital-e = "motion-serifed"
capital-f = "motion-serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "motion-serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "curly-motion-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing-curly-tailed"
capital-r = "curly-motion-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-motion-serifed"

j = "flat-hook-serifed"
k = "curly"
l = "serifed-flat-tailed"
t = "flat-hook"
x = "curly"
y = "curly-turn"
z = "curly"

turn-v         = "curly"
capital-gamma  = "motion-serifed"
lower-lambda   = "curly-turn"
cyrl-ka        = "curly"
cyrl-capital-u = "curly-turn"

zero = "slashed"
one   = "nobase"
two   = "curly-neck"
three = "flattop"
four  = "closed"
five  = "vertical-upper-left-bar"
six   = "open-contour"
seven = "curly-serifed"
eight = "two-circles"
nine  = "open-contour"

asterisk   = "low"
underscore = "low"

[buildPlans.iosevka-fusion.variants.upright]
a = "double-storey"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-flat-hook"
h = "straight"
i = "hooky"
m = "normal"
n = "straight"
v = "curly"
w = "curly"

[buildPlans.iosevka-fusion.variants.italic]
a = "single-storey-tailed"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "double-storey"
h = "tailed"
i = "serifed-flat-tailed"
m = "tailed"
n = "tailed"
v = "cursive"
w = "cursive"

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.slopes]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 576
menu  = 5
css   = "normal"
