[buildPlans.iosevka-fusion]
family  = "Iosevka Fusion"
spacing = "fixed"
serifs  = "sans"

[buildPlans.iosevka-fusion.variants.design]
capital-a = "curly-serifless"
capital-g = "toothless-rounded-serifless-capped"
capital-j = "flat-hook-serifed"
capital-k = "curly"
capital-q = "crossing-curly-tailed"
capital-r = "curly"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"

i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
t = "flat-hook"

turn-v         = "curly"
lower-lambda   = "curly-turn"
cyrl-ka        = "curly"
cyrl-capital-u = "curly-turn"

zero = "slashed"
one   = "nobase"
two   = "curly-neck"
three = "twoarcs"
four  = "closed"
five  = "vertical-upper-left-bar"
six   = "open-contour"
seven = "curly-serifless"
eight = "two-circles"
nine  = "open-contour"

asterisk   = "hex-low"
underscore = "low"
paren = "large-contour"

[buildPlans.iosevka-fusion.variants.upright]
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-flat-hook"
k = "curly"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
z = "curly-serifless"

[buildPlans.iosevka-fusion.variants.italic]
f = "flat-hook-tailed-crossbar-at-x-height"
g = "double-storey"
k = "cursive"
v = "cursive"
w = "cursive"
x = "cursive"
y = "cursive-flat-hook"
z = "cursive"

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.slopes]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 576
menu  = 5
css   = "normal"
