[buildPlans.iosevka-fusion]
family      = "Iosevka Fusion"
spacing     = "fixed"
serifs      = "sans"

[buildPlans.iosevka-fusion.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "curly"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"

c = "serifless"
h = "straight"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless"
s = "serifless"
t = "flat-hook"
y = "cursive-flat-hook"

zero = "slashed-split-oval"
three = "two-arcs"
five = "oblique-upper-left-bar"
seven = "straight-serifless"
eight = "crossing-asymmetric"

diacritic-dot = "square"
punctuation-dot = "square"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright"
ampersand = "closed"
at = "threefold-tall"
dollar = "through"
percent = "dots"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
cent = "through"

[buildPlans.iosevka-fusion.variants.upright]
a = "double-storey-serifless"
b = "toothless-corner"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
k = "straight-serifless"
m = "earless-corner-double-arch"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
u = "toothless-corner"
v = "straight"
w = "straight"
x = "straight-serifless"
z = "straight-serifless"

one = "base"
two = "straight-neck"
four = "semi-open"
six = "straight-bar"
nine = "straight-bar"

[buildPlans.iosevka-fusion.variants.italic]
a = "double-storey-serifless"
b = "toothed"
d = "toothed-serifless"
e = "rounded"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
k = "curly-serifless"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
u = "toothed"
v = "curly"
w = "curly"
x = "curly-serifless"
z = "curly-serifless"

one = "no-base"
two = "curly-neck"
four = "closed"
six = "closed-contour"
nine = "closed-contour"

[buildPlans.iosevka-fusion.weights.thin]
shape = 100
menu  = 100
css   = 100

[buildPlans.iosevka-fusion.weights.extralight]
shape = 200
menu  = 200
css   = 200

[buildPlans.iosevka-fusion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevka-fusion.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-fusion.weights.semibold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.weights.extrabold]
shape = 800
menu  = 800
css   = 800

[buildPlans.iosevka-fusion.weights.heavy]
shape = 900
menu  = 900
css   = 900

[buildPlans.iosevka-fusion.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-fusion.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.iosevka-fusion.metric-override]
leading = 1350
sb = 60
xHeight = 530
